name: 'push-github'
description: 'git push to github repo'
author: 'cj645'
branding:
  icon: upload-cloud
  color: green
inputs:
  github_token:
    description: 'GitHub token or PAT token'
    required: false
    default: ${{ github.token }}
  github_url:
    description: 'GitHub url or GitHub Enterprise url'
    required: false
    default: ${{ github.server_url }}
  branch:
    description: 'Specify branch to be used'
    required: false
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
runs:
  using: 'node20'
  main: 'start.js'
